-- Legacy UUID columns were migration bridges from old varchar UUID primary keys
-- to current INT primary keys. Runtime code no longer writes them. They must
-- allow NULL, and their old unique indexes must not reject new rows that omit
-- legacy UUID values.

SET @table_name := 'designs';
SET @unique_index_name := 'ux_designs_legacy_uuid';
SET @lookup_index_name := 'idx_designs_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_metals';
SET @unique_index_name := 'ux_design_metals_legacy_uuid';
SET @lookup_index_name := 'idx_design_metals_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_gemstones';
SET @unique_index_name := 'ux_design_gemstones_legacy_uuid';
SET @lookup_index_name := 'idx_design_gemstones_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_labors';
SET @unique_index_name := 'ux_design_labors_legacy_uuid';
SET @lookup_index_name := 'idx_design_labors_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_findings';
SET @unique_index_name := 'ux_design_findings_legacy_uuid';
SET @lookup_index_name := 'idx_design_findings_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_process_stages';
SET @unique_index_name := 'ux_design_process_stages_legacy_uuid';
SET @lookup_index_name := 'idx_design_process_stages_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_vendors';
SET @unique_index_name := 'ux_design_vendors_legacy_uuid';
SET @lookup_index_name := 'idx_design_vendors_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_pricing_tiers';
SET @unique_index_name := 'ux_design_pricing_tiers_legacy_uuid';
SET @lookup_index_name := 'idx_design_pricing_tiers_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_stl_files';
SET @unique_index_name := 'ux_design_stl_files_legacy_uuid';
SET @lookup_index_name := 'idx_design_stl_files_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_history';
SET @unique_index_name := 'ux_design_history_legacy_uuid';
SET @lookup_index_name := 'idx_design_history_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_relevant';
SET @unique_index_name := 'ux_design_relevant_legacy_uuid';
SET @lookup_index_name := 'idx_design_relevant_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @table_name := 'design_media_library';
SET @unique_index_name := 'ux_design_media_library_legacy_uuid';
SET @lookup_index_name := 'idx_design_media_library_legacy_uuid';
SET @column_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND COLUMN_NAME = 'legacy_uuid');
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @unique_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` DROP INDEX `', @unique_index_name, '`'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('ALTER TABLE `', @table_name, '` MODIFY `legacy_uuid` VARCHAR(36) NULL DEFAULT NULL'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF(@column_exists > 0, CONCAT('UPDATE `', @table_name, '` SET `legacy_uuid` = NULL WHERE TRIM(COALESCE(`legacy_uuid`, '''')) = '''''), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @index_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table_name AND INDEX_NAME = @lookup_index_name);
SET @sql := IF(@column_exists > 0 AND @index_exists = 0, CONCAT('ALTER TABLE `', @table_name, '` ADD INDEX `', @lookup_index_name, '` (`legacy_uuid`)'), 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
