CREATE TABLE IF NOT EXISTS notifications (
  id VARCHAR(36) NOT NULL,
  recipient_user_id VARCHAR(36) NOT NULL,
  company_id VARCHAR(36) NULL,
  branch_id VARCHAR(36) NULL,
  type VARCHAR(60) NOT NULL,
  priority VARCHAR(8) NOT NULL DEFAULT 'P1',
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  entity_type VARCHAR(60) NULL,
  entity_id VARCHAR(36) NULL,
  action_url TEXT NULL,
  channel_in_app TINYINT(1) NOT NULL DEFAULT 1,
  channel_email TINYINT(1) NOT NULL DEFAULT 0,
  channel_push TINYINT(1) NOT NULL DEFAULT 0,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  read_at DATETIME NULL,
  metadata JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_notifications_user_created (recipient_user_id, created_at),
  KEY idx_notifications_user_unread (recipient_user_id, is_read),
  KEY idx_notifications_entity (entity_type, entity_id)
);
