export enum SpiffLedgerEvent {
  QUOTE_CREATED = 'QUOTE_CREATED',
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_VALUE_BONUS = 'ORDER_VALUE_BONUS',
  FAST_CLOSE_BONUS = 'FAST_CLOSE_BONUS',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
}
